spring:
  application:
    name: Library Management System

  datasource:
    datasource:
      url: jdbc:postgresql://localhost:5432/capstoneapidb
      username: postgres
      password: mugwadavid

    jpa:
      hibernate:
        ddl-auto: update
      show-sql: true
      properties:
        hibernate:
